[alias]
hosttools-raw = "run --bin hosttools"
hosttools = "hosttools-raw --"
hclippy = "clippy -p hosttools"
cross = "hosttools cross"
xbuild = "cross build --"
xclippy = "cross clippy --"
xclippy-json = "hosttools-raw --message-format=json -- cross clippy -- --message-format=json-diagnostic-rendered-ansi"
image = "hosttools image"
qemu = "hosttools qemu"
gdb-attach = "hosttools gdb-attach"
gdb-split = "hosttools gdb-split"

[profile.release]
lto = "fat"
