[package]
name = "mkimage"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fatfs = "0.3.5"
gpt = "2.0.0"
anyhow = "1.0.42"
cargo_metadata = "0.14.0"
