[package]
name = "kernel-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
struct-enum = { path = "../../lib/struct-enum" }
